# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App4-Driver' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'HEREMapsStarter'

  # Pods for App4-Driver

end
